### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by philippgille** [FiloSottile/mkcert#22]
I cloned the repo at commit 073ee25396d221758bcb1bb6948e299fcb2d0c1b.

When executing `make`, I get the following error:

```
GOPATH="/root/git/mkcert/.GOPATH" go install -v github.com/FiloSottile/mkcert
github.com/FiloSottile/mkcert
# github.com/FiloSottile/mkcert
.GOPATH/src/github.com/FiloSottile/mkcert/cert.go:67: undefined: x509.MarshalPKCS8PrivateKey
.GOPATH/src/github.com/FiloSottile/mkcert/cert.go:141: undefined: x509.MarshalPKCS8PrivateKey
Makefile:5: recipe for target 'mkcert' failed
make: *** [mkcert] Error 2
```

Am I missing some step for the installation?

**Comment by Mohammed90** [comment]
The project requires Go 1.10+

**Comment by philippgille** [comment]
Oh snap, I usually work on a machine with Go 1.10, but not this time.

Thanks!
